# Model

In [ ]:
from numpy.random import seed
seed(41)
from tensorflow import set_random_seed
set_random_seed(42)

from keras.layers import Input, Dense, Embedding, concatenate, dot
from keras.models import Model

########################
## Model
########################
# Configurations
user_pref_dim = 100
user_cont_dim = 100
item_pref_dim = 100
item_cont_dim = 100
ACTIVATION = 'relu'

# user input, cont for content
user_pref = Input(shape=(user_pref_dim, ), dtype='float', name='user_pref')
user_cont = Input(shape=(user_cont_dim, ), dtype='float', name='user_cont')
# item input
item_pref = Input(shape=(item_pref_dim, ), dtype='float', name='item_pref')
item_cont = Input(shape=(item_cont_dim, ), dtype='float', name='item_cont')

# user_layer
user_layer = concatenate([user_pref, user_cont])
user_layer = Dense(200, activation=ACTIVATION)(user_layer)
user_layer = Dense(100, activation=ACTIVATION)(user_layer)
user_layer = Dense(latent_dim, activation=None)(user_layer)

# item_layer
item_layer = concatenate([item_pref, item_cont])
item_layer = Dense(200, activation=ACTIVATION)(item_layer)
item_layer = Dense(100, activation=ACTIVATION)(item_layer)
item_layer = Dense(latent_dim, activation=None)(item_layer)

# output layer
output = dot([user_layer, item_layer], axes=1, normalize=False)
chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/pages/popup.html#
# Model configuration
model = Model(inputs=[user_pref, user_cont, item_pref, item_cont],
             outputs=output)
opt = RMSprop(lr=1e-3)
model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['acc'])

# fit
model.fit(
    [user_pref_data, user_cont_data, item_pref_data, item_cont_data],
    rating,
    epochs=50,
    batch_size=64
)

In [1]:
x = [1,2,3]
list(zip(x[:-1], x[1:]))

[(1, 2), (2, 3)]

In [ ]:
# evaluation

# Command Experiments

## tf.gather_nd example

In [12]:
import numpy as np
import tensorflow as tf

In [16]:
x = np.reshape(range(25), [5,5])

In [17]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
urand = [1, 2, 3]
irand = [2, 3, 4]
ui_rand = np.transpose(np.vstack([urand, irand]))
print(ui_rand)
sess = tf.Session()
sess.run(tf.gather_nd(x, ui_rand))

[[1 2]
 [2 3]
 [3 4]]


array([ 7, 13, 19])

## small things

NameError: name 'xrange' is not defined